version: '3.8'

services:
  app:
    container_name: solo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Se necess√°rio, defina JWT_SECRET e outras vars aqui ou no painel do Coolify
      # JWT_SECRET: ${JWT_SECRET} 
    volumes:
      - ./src/database/database.sqlite:/usr/src/app/src/database/database.sqlite
    restart: always
